name: Data Validation

on:
  push:
    branches:
      - main
    paths:
      - "data/**"  # Trigger only when files in the data folder are modified
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pgs3cr3t
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install pandas scipy psycopg2-binary

      - name: List Repository Files
        run: |
          ls -R

      - name: Run Data Validation Script
        run: |
          python data_processing/data_validation_script.py

      - name: Upload Enriched Data to GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add enriched_data.csv
          git commit -m "Add enriched data file from data validation"
          git push origin main

