name: Data Validation and Enrichment

on:
  push:
    branches:
      - main
    paths:
      - "data/**"  # Trigger only when files in the data folder are modified
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install pandas scipy

      - name: Run Data Validation Script
        run: |
          python data_processing/data_validation_script.py

      - name: Initialize Master Data
        run: |
          python data_processing/initialize_master_data.py

      - name: Run Data Enrichment Script
        run: |
          python data_processing/data_enrichment_script.py

      - name: Verify Enriched Data File Exists
        run: |
          if [ ! -f "data/enriched_data.csv" ]; then
            echo "Error: enriched_data.csv not found!"
            exit 1
          fi

      - name: Set up Git authentication
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Verify Data Directory Contents
        run: |
          echo "Checking data directory contents:"
          ls data/

      - name: Commit and Push Changes
        run: |
          git add data/enriched_data.csv
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Add enriched data file from data processing"
            git push origin main
          fi

      - name: Add master_data.sqlite to Git
        run: |
          git add data/master_data.sqlite
          if git diff-index --quiet HEAD; then
            echo "No changes to commit for master_data.sqlite."
          else
            git commit -m "Add master_data.sqlite"
            git push origin main
          fi
